/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/me/h1_inspire_service.worktrees/Yxy_Dev/hand_idl/inspire_hand_touch.idl
  Source: inspire_hand_touch.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "inspire_hand_touch.hpp"

// #include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

#include <iostream>
// #include <org/eclipse/cyclonedds/util/ostream_operators.hpp>
namespace inspire
{

template<typename T>
std::ostream& operator<<(std::ostream& os, const std::vector<T>& vec)
{
    os << "[";
    for (size_t i = 0; i < vec.size(); ++i)
    {
        os << vec[i];
        if (i != vec.size() - 1)
        {
            os << ", ";
        }
    }
    os << "]";
    return os;
}
std::ostream& operator<<(std::ostream& os, inspire_hand_touch const& rhs)
{
  (void) rhs;
  os << "[";
  os << "fingerone_tip_touch: " << rhs.fingerone_tip_touch();
  os << ", fingerone_top_touch: " << rhs.fingerone_top_touch();
  os << ", fingerone_palm_touch: " << rhs.fingerone_palm_touch();
  os << ", fingertwo_tip_touch: " << rhs.fingertwo_tip_touch();
  os << ", fingertwo_top_touch: " << rhs.fingertwo_top_touch();
  os << ", fingertwo_palm_touch: " << rhs.fingertwo_palm_touch();
  os << ", fingerthree_tip_touch: " << rhs.fingerthree_tip_touch();
  os << ", fingerthree_top_touch: " << rhs.fingerthree_top_touch();
  os << ", fingerthree_palm_touch: " << rhs.fingerthree_palm_touch();
  os << ", fingerfour_tip_touch: " << rhs.fingerfour_tip_touch();
  os << ", fingerfour_top_touch: " << rhs.fingerfour_top_touch();
  os << ", fingerfour_palm_touch: " << rhs.fingerfour_palm_touch();
  os << ", fingerfive_tip_touch: " << rhs.fingerfive_tip_touch();
  os << ", fingerfive_top_touch: " << rhs.fingerfive_top_touch();
  os << ", fingerfive_middle_touch: " << rhs.fingerfive_middle_touch();
  os << ", fingerfive_palm_touch: " << rhs.fingerfive_palm_touch();
  os << ", palm_touch: " << rhs.palm_touch();
  os << "]";
  return os;
}

} //namespace inspire

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::inspire::inspire_hand_touch>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerone_tip_touch
  props.push_back(entity_properties_t(1, 1, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerone_top_touch
  props.push_back(entity_properties_t(1, 2, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerone_palm_touch
  props.push_back(entity_properties_t(1, 3, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingertwo_tip_touch
  props.push_back(entity_properties_t(1, 4, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingertwo_top_touch
  props.push_back(entity_properties_t(1, 5, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingertwo_palm_touch
  props.push_back(entity_properties_t(1, 6, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerthree_tip_touch
  props.push_back(entity_properties_t(1, 7, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerthree_top_touch
  props.push_back(entity_properties_t(1, 8, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerthree_palm_touch
  props.push_back(entity_properties_t(1, 9, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerfour_tip_touch
  props.push_back(entity_properties_t(1, 10, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerfour_top_touch
  props.push_back(entity_properties_t(1, 11, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerfour_palm_touch
  props.push_back(entity_properties_t(1, 12, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerfive_tip_touch
  props.push_back(entity_properties_t(1, 13, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerfive_top_touch
  props.push_back(entity_properties_t(1, 14, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerfive_middle_touch
  props.push_back(entity_properties_t(1, 15, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::fingerfive_palm_touch
  props.push_back(entity_properties_t(1, 16, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::palm_touch

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

