//inspire_hand_touch.idl
module inspire
{
    struct inspire_hand_touch
    {
        sequence<int16,9>   fingerone_tip_touch;      // 小拇指指端触觉数据
        sequence<int16,96>  fingerone_top_touch;      // 小拇指指尖触觉数据
        sequence<int16,80>  fingerone_palm_touch;     // 小拇指指腹触觉数据
        sequence<int16,9>   fingertwo_tip_touch;      // 无名指指端触觉数据
        sequence<int16,96>  fingertwo_top_touch;      // 无名指指尖触觉数据
        sequence<int16,80>  fingertwo_palm_touch;     // 无名指指腹触觉数据
        sequence<int16,9>   fingerthree_tip_touch;    // 中指指端触觉数据
        sequence<int16,96>  fingerthree_top_touch;    // 中指指尖触觉数据
        sequence<int16,80>  fingerthree_palm_touch;   // 中指指腹触觉数据
        sequence<int16,9>   fingerfour_tip_touch;     // 食指指端触觉数据
        sequence<int16,96>  fingerfour_top_touch;     // 食指指尖触觉数据
        sequence<int16,80>  fingerfour_palm_touch;    // 食指指腹触觉数据
        sequence<int16,9>   fingerfive_tip_touch;     // 大拇指指端触觉数据
        sequence<int16,96>  fingerfive_top_touch;     // 大拇指尖触觉数据
        sequence<int16,9>   fingerfive_middle_touch;  // 大拇指指中触觉数据
        sequence<int16,96>  fingerfive_palm_touch;    // 大拇指指腹触觉数据
        sequence<int16,112> palm_touch;                // 掌心触觉数据
    };

};
